// components/faculty/AddFaculty.jsx
import React, { useState, useEffect } from "react";
import { useNavigate, Link } from "react-router-dom";
import { facultyAPI } from "../../services/api";
import { courseAPI } from "../../services/api";
import {
  Save,
  X,
  Calendar,
  User,
  Phone,
  Mail,
  Home,
  DollarSign,
} from "lucide-react";
import "./AddFaculty.css";

const AddFaculty = () => {
  const navigate = useNavigate();

  const [formData, setFormData] = useState({
    dateOfJoining: "",
    facultyName: "",
    fathersName: "",
    shift: "",
    lunchTime: "",
    dateOfBirth: "",
    email: "",
    basicStipend: "",
    mobileNo: "",
    whatsappNo: "",
    address: "",
    fatherContactNo: "",
    motherContactNo: "",
    dateOfLeaving: "",
    courseAllotted: "",
  });

  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [autoGeneratedNo] = useState(
    "FAC" + Math.floor(1000 + Math.random() * 9000)
  );

  // Format name to Proper Case
  const formatName = (name) => {
    if (!name) return "";
    return name
      .toLowerCase()
      .split(" ")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  };

  // Format phone number to exactly 10 digits
  const formatPhoneNumber = (phone) => {
    if (!phone) return "";
    // Remove all non-digits and take first 10 characters
    const digits = phone.replace(/\D/g, "").slice(0, 10);
    return digits;
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;

    let formattedValue = value;

    // Apply formatting based on field type
    if (name === "facultyName" || name === "fathersName") {
      formattedValue = formatName(value);
    } else if (
      name === "mobileNo" ||
      name === "whatsappNo" ||
      name === "fatherContactNo" ||
      name === "motherContactNo"
    ) {
      formattedValue = formatPhoneNumber(value);
    } else if (name === "basicStipend") {
      formattedValue = value.replace(/[^0-9]/g, "");
    } else if (name === "email") {
      formattedValue = value;
    } else if (name === "address") {
      formattedValue = value.charAt(0).toUpperCase() + value.slice(1);
    }

    setFormData({
      ...formData,
      [name]: formattedValue,
    });

    // Clear error when user starts typing
    if (errors[name]) {
      setErrors({
        ...errors,
        [name]: "",
      });
    }
  };

  const [courses, setCourses] = useState([]);
  const [loadingCourses, setLoadingCourses] = useState(false);
  const [courseError, setCourseError] = useState(null);
  // Add this useEffect after other state declarations
  useEffect(() => {
    fetchCourses();
  }, []);

  // Add this function to fetch courses
  const fetchCourses = async () => {
    try {
      setLoadingCourses(true);
      setCourseError(null);

      const response = await courseAPI.getActiveCourses();

      if (response.data.success) {
        setCourses(response.data.data || []);
      } else {
        throw new Error(response.data.message || "Failed to load courses");
      }
    } catch (err) {
      console.error("Error fetching courses:", err);
      setCourseError(
        err.message || "Failed to load courses. Using default options."
      );

      // Fallback courses in case API fails
      setCourses([
        {
          _id: "1",
          courseFullName: "B.Tech Computer Science",
          courseShortName: "BTech CS",
        },
        { _id: "2", courseFullName: "MBA", courseShortName: "MBA" },
        { _id: "3", courseFullName: "BBA", courseShortName: "BBA" },
        { _id: "4", courseFullName: "BCA", courseShortName: "BCA" },
        { _id: "5", courseFullName: "M.Tech", courseShortName: "MTech" },
      ]);
    } finally {
      setLoadingCourses(false);
    }
  };

  const validateForm = () => {
    const newErrors = {};
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    const phoneRegex = /^\d{10}$/;

    // Required field validation
    const requiredFields = [
      "dateOfJoining",
      "facultyName",
      "fathersName",
      "shift",
      "lunchTime",
      "dateOfBirth",
      "email",
      "basicStipend",
      "mobileNo",
      "address",
      "fatherContactNo",
      "motherContactNo",
      "courseAllotted",
    ];

    requiredFields.forEach((field) => {
      if (!formData[field] || !formData[field].toString().trim()) {
        newErrors[field] = "This field is required";
      }
    });

    // Email validation
    if (formData.email && !emailRegex.test(formData.email)) {
      newErrors.email = "Please enter a valid email address";
    }

    // Phone number validation (must be exactly 10 digits)
    const phoneFields = [
      "mobileNo",
      "whatsappNo",
      "fatherContactNo",
      "motherContactNo",
    ];
    phoneFields.forEach((field) => {
      if (formData[field] && !phoneRegex.test(formData[field])) {
        newErrors[field] = "Phone number must be exactly 10 digits";
      }
    });

    // WhatsApp number is optional, but if provided, must be 10 digits
    if (formData.whatsappNo && !phoneRegex.test(formData.whatsappNo)) {
      newErrors.whatsappNo = "WhatsApp number must be exactly 10 digits";
    }

    // Basic stipend validation
    if (formData.basicStipend && parseInt(formData.basicStipend) <= 0) {
      newErrors.basicStipend = "Stipend must be greater than 0";
    }

    // Date validation: Date of joining should be after date of birth
    if (formData.dateOfJoining && formData.dateOfBirth) {
      const joinDate = new Date(formData.dateOfJoining);
      const birthDate = new Date(formData.dateOfBirth);
      if (joinDate < birthDate) {
        newErrors.dateOfJoining =
          "Date of joining cannot be before date of birth";
      }
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validateForm()) {
      alert("Please fill all required fields before submitting.");
      return;
    }

    setIsSubmitting(true);

    try {
      // Prepare data for API
      const facultyData = {
        facultyNo: autoGeneratedNo,
        facultyName: formData.facultyName,
        fathersName: formData.fathersName,
        dateOfJoining: formData.dateOfJoining,
        dateOfBirth: formData.dateOfBirth,
        shift: formData.shift,
        lunchTime: formData.lunchTime,
        email: formData.email,
        mobileNo: formData.mobileNo,
        whatsappNo: formData.whatsappNo || formData.mobileNo, // Default to mobile
        address: formData.address,
        fatherContactNo: formData.fatherContactNo,
        motherContactNo: formData.motherContactNo,
        basicStipend: parseFloat(formData.basicStipend) || 0,
        status: "active", // Default status
        dateOfLeaving: formData.dateOfLeaving || null,
        courseAssigned: formData.courseAllotted,
      };

      // Call API
      const response = await facultyAPI.createFaculty(facultyData);

      if (response.data.success) {
        alert("Faculty added successfully!");

        // Reset form
        setFormData({
          dateOfJoining: "",
          facultyName: "",
          fathersName: "",
          shift: "",
          lunchTime: "",
          dateOfBirth: "",
          email: "",
          basicStipend: "",
          mobileNo: "",
          whatsappNo: "",
          address: "",
          fatherContactNo: "",
          motherContactNo: "",
          dateOfLeaving: "",
          courseAllotted: "",
        });
        setErrors({});

        // Navigate back to faculty list
        navigate("/admin/faculty");
      } else {
        throw new Error(response.data.message || "Failed to add faculty");
      }
    } catch (err) {
      console.error("Error adding faculty:", err);
      alert(
        err.response?.data?.message ||
          "Failed to add faculty. Please try again."
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleCancel = () => {
    if (
      window.confirm(
        "Are you sure you want to cancel? All unsaved changes will be lost."
      )
    ) {
      navigate("/admin/faculty");
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter") {
      e.preventDefault();
      const form = e.target.form;
      const focusableElements = form.querySelectorAll(
        'input:not([type="radio"]):not([type="checkbox"]), select, textarea, button'
      );
      const currentIndex = Array.from(focusableElements).indexOf(e.target);
      if (currentIndex < focusableElements.length - 1) {
        const nextElement = focusableElements[currentIndex + 1];
        if (
          nextElement.tagName !== "BUTTON" ||
          currentIndex === focusableElements.length - 2
        ) {
          nextElement.focus();
        }
      }
    }
  };

  const handleReset = () => {
    setFormData({
      dateOfJoining: "",
      facultyName: "",
      fathersName: "",
      shift: "",
      lunchTime: "",
      dateOfBirth: "",
      email: "",
      basicStipend: "",
      mobileNo: "",
      whatsappNo: "",
      address: "",
      fatherContactNo: "",
      motherContactNo: "",
      dateOfLeaving: "",
      courseAllotted: "",
    });
    setErrors({});
  };

  return (
    <div className="new-enquiry-container">
      {/* Header */}
      <div className="page-header">
        <div className="header-left">
          <Link to="/admin/faculty" className="back-link">
            <X size={20} />
            Cancel
          </Link>
          <div>
            <h1>Add New Faculty</h1>
            <p>Fill in the details for new faculty member</p>
          </div>
        </div>
        <div className="header-actions">
          <button
            onClick={handleSubmit}
            disabled={isSubmitting}
            className="btn-primary"
            type="submit"
          >
            <Save size={18} />
            {isSubmitting ? "Submitting..." : "Add Faculty"}
          </button>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="enquiry-form">
        {/* Section 1: Faculty Details */}
        <div className="form-card">
          <div className="card-header">
            <User size={20} />
            <h3>Faculty Details</h3>
          </div>
          <div className="card-content">
            <div className="form-grid">
              <div className="form-group">
                <label>Faculty No</label>
                <input
                  type="text"
                  value={autoGeneratedNo}
                  readOnly
                  className="enquiry-no"
                />
              </div>

              <div className="form-group">
                <label>
                  Date of Joining <span className="required-star">*</span>
                </label>
                <input
                  type="date"
                  name="dateOfJoining"
                  value={formData.dateOfJoining}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  max={new Date().toISOString().split("T")[0]}
                  className={errors.dateOfJoining ? "error-field" : ""}
                />
                {errors.dateOfJoining && (
                  <span className="error-text">{errors.dateOfJoining}</span>
                )}
              </div>

              <div className="form-group">
                <label>
                  Faculty Name <span className="required-star">*</span>
                </label>
                <input
                  type="text"
                  name="facultyName"
                  value={formData.facultyName}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  placeholder="Full name of faculty"
                  className={errors.facultyName ? "error-field" : ""}
                />
                {errors.facultyName && (
                  <span className="error-text">{errors.facultyName}</span>
                )}
              </div>

              <div className="form-group">
                <label>
                  Father's Name <span className="required-star">*</span>
                </label>
                <input
                  type="text"
                  name="fathersName"
                  value={formData.fathersName}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  placeholder="Father's name"
                  className={errors.fathersName ? "error-field" : ""}
                />
                {errors.fathersName && (
                  <span className="error-text">{errors.fathersName}</span>
                )}
              </div>

              <div className="form-group">
                <label>
                  Date of Birth <span className="required-star">*</span>
                </label>
                <input
                  type="date"
                  name="dateOfBirth"
                  value={formData.dateOfBirth}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  max={new Date().toISOString().split("T")[0]}
                  className={errors.dateOfBirth ? "error-field" : ""}
                />
                {errors.dateOfBirth && (
                  <span className="error-text">{errors.dateOfBirth}</span>
                )}
              </div>

              <div className="form-group">
                <label>
                  Course Allotted <span className="required-star">*</span>
                </label>
                <select
                  name="courseAllotted"
                  value={formData.courseAllotted}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  className={errors.courseAllotted ? "error-field" : ""}
                  disabled={loadingCourses}
                >
                  <option value="">
                    {loadingCourses ? "Loading courses..." : "Select Course"}
                  </option>
                  {courses.map((course) => (
                    <option key={course._id} value={course.courseFullName}>
                      {" "}
                      {/* Send name */}
                      {course.courseFullName}
                      {course.courseShortName
                        ? ` (${course.courseShortName})`
                        : ""}
                    </option>
                  ))}
                  <option value="">Not Allotted</option>
                  <option value="general_subjects">General Subjects</option>
                  <option value="not_allotted">Not Allotted</option>
                </select>

                {/* Show loading or error messages */}
                {loadingCourses && (
                  <span className="loading-text">Loading courses...</span>
                )}
                {courseError && !loadingCourses && (
                  <span
                    className="error-text"
                    style={{ color: "orange", fontSize: "12px" }}
                  >
                    ⚠️ {courseError}
                  </span>
                )}
                {errors.courseAllotted && (
                  <span className="error-text">{errors.courseAllotted}</span>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Section 2: Work Details */}
        <div className="form-card">
          <div className="card-header">
            <Calendar size={20} />
            <h3>Work Details</h3>
          </div>
          <div className="card-content">
            <div className="form-grid">
              <div className="form-group">
                <label>
                  Faculty Timing Shift <span className="required-star">*</span>
                </label>
                <select
                  name="shift"
                  value={formData.shift}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  className={errors.shift ? "error-field" : ""}
                >
                  <option value="">Select Shift</option>
                  <option value="Morning">Morning (7:00 AM - 2:00 PM)</option>
                  <option value="Afternoon">
                    Afternoon (12:00 PM - 7:00 PM)
                  </option>
                  <option value="Evening">Evening (2:00 PM - 9:00 PM)</option>
                  <option value="Full-day">Full Day (9:00 AM - 5:00 PM)</option>
                </select>
                {errors.shift && (
                  <span className="error-text">{errors.shift}</span>
                )}
              </div>

              <div className="form-group">
                <label>
                  Faculty Lunch Time <span className="required-star">*</span>
                </label>
                <input
                  type="time"
                  name="lunchTime"
                  value={formData.lunchTime}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  className={errors.lunchTime ? "error-field" : ""}
                />
                {errors.lunchTime && (
                  <span className="error-text">{errors.lunchTime}</span>
                )}
              </div>

              <div className="form-group">
                <label>Date of Leaving</label>
                <input
                  type="date"
                  name="dateOfLeaving"
                  value={formData.dateOfLeaving}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  min={formData.dateOfJoining}
                />
              </div>

              <div className="form-group">
                <label>
                  Basic Stipend (₹) <span className="required-star">*</span>
                </label>
                <input
                  type="text"
                  name="basicStipend"
                  value={formData.basicStipend}
                  onChange={handleInputChange}
                  onKeyDown={handleKeyDown}
                  placeholder="Monthly stipend amount"
                  className={errors.basicStipend ? "error-field" : ""}
                />
                {errors.basicStipend && (
                  <span className="error-text">{errors.basicStipend}</span>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Section 3: Contact Information */}
        <div className="form-sections-row">
          {/* Left Column - Contact Details */}
          <div className="form-column">
            <div className="form-card">
              <div className="card-header">
                <Phone size={20} />
                <h3>Contact Information</h3>
              </div>
              <div className="card-content">
                <div className="form-grid">
                  <div className="form-group">
                    <label>
                      Mobile No <span className="required-star">*</span>
                    </label>
                    <input
                      type="tel"
                      name="mobileNo"
                      value={formData.mobileNo}
                      onChange={handleInputChange}
                      onKeyDown={handleKeyDown}
                      placeholder="10 digit mobile number"
                      maxLength="10"
                      className={errors.mobileNo ? "error-field" : ""}
                    />
                    {errors.mobileNo && (
                      <span className="error-text">{errors.mobileNo}</span>
                    )}
                  </div>

                  <div className="form-group">
                    <label>WhatsApp No</label>
                    <input
                      type="tel"
                      name="whatsappNo"
                      value={formData.whatsappNo}
                      onChange={handleInputChange}
                      onKeyDown={handleKeyDown}
                      placeholder="10 digit WhatsApp number"
                      maxLength="10"
                      className={errors.whatsappNo ? "error-field" : ""}
                    />
                    {errors.whatsappNo && (
                      <span className="error-text">{errors.whatsappNo}</span>
                    )}
                  </div>

                  <div className="form-group">
                    <label>
                      Email ID <span className="required-star">*</span>
                    </label>
                    <input
                      type="email"
                      name="email"
                      value={formData.email}
                      onChange={handleInputChange}
                      onKeyDown={handleKeyDown}
                      placeholder="email@example.com"
                      className={errors.email ? "error-field" : ""}
                    />
                    {errors.email && (
                      <span className="error-text">{errors.email}</span>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column - Parent Contact Details */}
          <div className="form-column">
            <div className="form-card">
              <div className="card-header">
                <User size={20} />
                <h3>Parent Contact Details</h3>
              </div>
              <div className="card-content">
                <div className="form-grid">
                  <div className="form-group">
                    <label>
                      Father Contact No <span className="required-star">*</span>
                    </label>
                    <input
                      type="tel"
                      name="fatherContactNo"
                      value={formData.fatherContactNo}
                      onChange={handleInputChange}
                      onKeyDown={handleKeyDown}
                      placeholder="10 digit contact number"
                      maxLength="10"
                      className={errors.fatherContactNo ? "error-field" : ""}
                    />
                    {errors.fatherContactNo && (
                      <span className="error-text">
                        {errors.fatherContactNo}
                      </span>
                    )}
                  </div>

                  <div className="form-group">
                    <label>
                      Mother Contact No <span className="required-star">*</span>
                    </label>
                    <input
                      type="tel"
                      name="motherContactNo"
                      value={formData.motherContactNo}
                      onChange={handleInputChange}
                      onKeyDown={handleKeyDown}
                      placeholder="10 digit contact number"
                      maxLength="10"
                      className={errors.motherContactNo ? "error-field" : ""}
                    />
                    {errors.motherContactNo && (
                      <span className="error-text">
                        {errors.motherContactNo}
                      </span>
                    )}
                  </div>

                  <div className="form-group full-width">
                    <label>
                      Address <span className="required-star">*</span>
                    </label>
                    <input
                      type="text"
                      name="address"
                      value={formData.address}
                      onChange={handleInputChange}
                      onKeyDown={handleKeyDown}
                      placeholder="Complete address"
                      className={errors.address ? "error-field" : ""}
                    />
                    {errors.address && (
                      <span className="error-text">{errors.address}</span>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Form Actions */}
        <div className="form-actions">
          <button type="button" onClick={handleReset} className="btn-reset">
            Reset Form
          </button>
          <button type="submit" disabled={isSubmitting} className="btn-submit">
            {isSubmitting ? "Submitting..." : "Add Faculty"}
          </button>
        </div>
      </form>
    </div>
  );
};

export default AddFaculty;
